/* CREAR LA CONEXIÓN */

/* CREAR SCIPTS */
DROP TABLE TEMPORAL;
DROP TABLE PAIS;
DROP TABLE REGION;
DROP TABLE DEPARTAMENTO;
DROP TABLE MUNICIPIO;

TRUNCATE TABLE DEPARTAMENTO;


/* SCRIPT CREACION TABLA TEMPORAL */
CREATE TABLE TEMPORAL(
    nombre_eleccion varchar2(100) not null,
    anio_eleccion   number(4,0) not null,
    pais            varchar2(100) not null,
    region          varchar2(100) not null,
    depto           varchar2(100) not null,
    municipio       varchar2(100) not null,
    partido         varchar2(100) not null,
    nombre_partido  varchar2(100) not null,
    sexo            varchar2(100) not null,
    raza            varchar2(100) not null,
    analfabetos     integer not null,
    alfabetos       integer not null,
    sexo_           varchar2(100) not null,
    raza_           varchar2(100) not null,
    primaria        integer not null,
    nivel_medio     integer not null,
    universitarios  integer not null
);

/* SCRIPT CREACION TABLAS DEL ER */
CREATE TABLE PAIS(
    idPais INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2(100) not null,
    PRIMARY KEY(idPais)
);
CREATE TABLE REGION(
    idRegion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre  varchar2(100) not null, 
    pais    integer,
    PRIMARY KEY(idRegion),
    FOREIGN KEY (pais) REFERENCES PAIS (idPais) ON DELETE CASCADE
);
CREATE TABLE DEPARTAMENTO(
    idDepartamento INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2(100) not null,
    region integer,
    PRIMARY KEY(idDepartamento),
    FOREIGN KEY (region) REFERENCES REGION (idRegion) ON DELETE CASCADE
);
CREATE TABLE MUNICIPIO(
    idMunicipio INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2(100) not null,
    departamento integer,
    PRIMARY KEY (idMunicipio),
    FOREIGN KEY (departamento) REFERENCES DEPARTAMENTO(idDepartamento) ON DELETE CASCADE
);


CREATE TABLE ELECCION(
    idEleccion INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre varchar2 (100) not null,
    anio number(4,0),
    PRIMARY KEY(idEleccion)
);
CREATE TABLE PARTIDO(
    idPartido INTEGER GENERATED BY DEFAULT AS IDENTITY,
    partido     varchar2 (100) not null,
    nombre      varchar2 (100) not null,
    PRIMARY KEY(idPartido)
);
CREATE TABLE ELECCIONPARTIDO(
    idEP INTEGER GENERATED BY DEFAULT AS IDENTITY, 
    eleccion    INTEGER, 
    partido     INTEGER, 
    PRIMARY KEY (idEP), 
    FOREIGN KEY (Eleccion) REFERENCES ELECCION (IdEleccion) ON DELETE CASCADE, 
    FOREIGN KEY (Partido) REFERENCES PARTIDO (IdPartido) ON DELETE CASCADE
);


CREATE TABLE RAZA(
    idRaza INTEGER GENERATED BY DEFAULT AS IDENTITY,
    raza varchar2(100) not null,
    PRIMARY KEY(idRaza)
);
CREATE TABLE GENERO(
    idGenero INTEGER GENERATED BY DEFAULT AS IDENTITY,
    genero varchar2(100) not null,
    PRIMARY KEY(idGenero)
);
CREATE TABLE DETALLEVOTOS(
    idDetalle INTEGER GENERATED BY DEFAULT AS IDENTITY,
    analfabetas     integer,
    alfabetas       integer,
    primaria        integer,
    medio           integer,
    universitario   integer,
    raza            integer,
    municipio       integer,
    eleccionpartido integer,
    genero          integer,
    PRIMARY KEY (idDetalle),
    FOREIGN KEY (raza)              REFERENCES RAZA (idRaza)            ON DELETE CASCADE,
    FOREIGN KEY (municipio)         REFERENCES MUNICIPIO (idMunicipio)  ON DELETE CASCADE,
    FOREIGN KEY (eleccionpartido)   REFERENCES ELECCIONPARTIDO (idEP)   ON DELETE CASCADE,
    FOREIGN KEY (genero)            REFERENCES GENERO (idGenero)        ON DELETE CASCADE
);

/*CREACION ARCHIVO .CTL Y .SH*/
--sqlldr system/1406@ORCL18 control = Ctrl.ctrl, DATA=DC.csv
--sqlldr system/1406 control = control.lst log=track.log

